#보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회하는 SQL문을 작성해주세요. 
#이때 결과는 보호 시작일이 빠른 순으로 조회해야합니다.
#indatetime이 작은게 정상.// in이 Outdatetime보다 크면 출력
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME 
FROM ANIMAL_INS 
LEFT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME


# LEFT JOIN ANIMAL_OUTS 
# ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
# WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
# ORDER BY ANIMAL_INS.DATETIME